### ISSUE TITLE
is_annotated column interpretation in splAdder versions 3.x

### ISSUE THREAD

**Issue by tbrunetti** [ratschlab/spladder#168]
Hi Andre,

I noticed after upgrading from version 2.x to 3.x of SplAdder, there is now a column called is_annotated. In version 2.x, I was just reading in the gtf file, and using the SJ files from STAR compared to the base pair positions of the event in splAdder to determine novelty of an event. Is this was the is_annotated column is doing? If so, what do the values of the numbers mean? In our intron retention data, I see values of 2 and 3 for this column.

Thanks!
Tonya

**Comment by akahles** [comment]
Dear Tonya,

Thanks a lot for reaching out. This information is indeed missing from the docs and I will add it as soon as possible. The number of is the binary encoding of whether isoform 1 and isoform 2 contain any introns that are not annotated. If all introns in the isoform are also present in the annotation, the corresponding bit is 1, otherwise it is 0. There are four possible combinations:

00 (0) --> isoform 1 has at least one "novel" intron, isoform 2 has at least one "novel" intron
01  (1) --> all introns in isoform 1 are in the annotation, isoform 2 has at least one "novel" intron
10  (2) --> isoform 1 has at least one "novel" intron, all introns in isoform 2 are in the annotation
11  (3) --> all introns in isoform 1 are in the annotation, all introns in isoform 2 are in the annotation

As isoform 2 for intron retentions does not contain any intron, it also cannot contain any novel introns, hence for isoform 2 all introns are always annotated by convention. This is also the reason, why you only see values 2 and 3.

Best,

Andre

**Comment by tbrunetti** [comment]
@akahles Thank you, this helps out a lot!

**Comment by perllb** [comment]
@akahles 
Thanks for clarifying this! 

I have a further question regarding this - how to know what is isoform1 and isoform2? 
E.g. in exon-skip events, is isoform1 exon spliced-out, or exon spliced-in? 

I also have an issue where every splice event on negative strand having is_annotated=3. This is the case with all splice types.
