### ISSUE TITLE
spladder v1.0.0: multi-exon skip detection enters data-dependent infinite loop

### ISSUE THREAD

**Issue by rschulzUK** [ratschlab/spladder#32]
Hi Andre,

Have run spladder v1.0.0 on two data sets: mouse strand-specific TruSeq mRNA (4 samples), and human unstranded TrueSeq mRNA (5 samples). Aligned both with Hisat2 v.2.0.3beta. Using the Gencode Comprehensive transcript models for analysis with spladder (mouse: vM9; human: v24). Split the data by chromosome and, for mouse, by strand. Spladder failed to terminate for mouse Chr 19, reverse strand, and human Chr 9. Aborting spladder (mouse) generated the following traceback message:

```
.................................................. - 50/300, found 169
.................................................. - 100/300, found 404
.................................................. - 150/300, found 586
.................................................. - 200/300, found 751
.................................................. - 250/300, found 851
............................Traceback (most recent call last):
  File "/home/rschulz/bin/spladder-1.0.0/python//spladder.py", line 309, in <module>
    spladder()
  File "/home/rschulz/bin/spladder-1.0.0/python//spladder.py", line 302, in spladder
    collect_events(CFG)
  File "/home/rschulz/bin/spladder-1.0.0/python/modules/alt_splice/collect.py", line 283, in collect_events
    idx_mult_exon_skip, exon_mult_exon_skip = detect_events(genes, 'mult_exon_skip', sp.where([x.is_alt for x in genes])[0], CFG)
  File "/home/rschulz/bin/spladder-1.0.0/python/modules/alt_splice/detect.py", line 385, in detect_events
    result_list = detect_wrapper(genes[idx], event_type, idx, None, log=CFG['verbose'])[0]        
  File "/home/rschulz/bin/spladder-1.0.0/python/modules/alt_splice/detect.py", line 349, in detect_wrapper
    return (detect_multipleskips(genes, gidx, log), idx)
  File "/home/rschulz/bin/spladder-1.0.0/python/modules/alt_splice/detect.py", line 71, in detect_multipleskips
    idx = sp.where((exist_path[i, k] + exist_path[k, :]) < exist_path[i, :])[0]
KeyboardInterrupt
```

The human spladder process also was at the same stage of processing according the the log (attached), but no traceback message was generated upon aborting the process.

I attach the complete output directories and the input GFF and pickle files. Happy to also provide the input BAMs if necessary.
[output_19_rev_aborted.zip](https://github.com/ratschlab/spladder/files/251654/output_19_rev_aborted.zip)
[output_9_aborted.zip](https://github.com/ratschlab/spladder/files/251659/output_9_aborted.zip)

Spladder was called like this (analogous for mouse):

```
#!/bin/bash
SPLADDER_HOME=/home/rschulz/bin/spladder-1.0.0/python/
CHR=$1

mkdir -p ./output_${CHR}

python $SPLADDER_HOME/spladder.py \
-a ./input/gencode.v24.annotation.$CHR.gff3 \
-b ./input/bam/Control1.$CHR.bam,./input/bam/Control2.$CHR.bam,./input/bam/HIV1.$CHR.bam,./input/bam/HIV2.$CHR.bam,./input/bam/HIV3.$CHR.bam \
-n 101 \
-o ./output_${CHR} \
-v y \
-c 2 \
-M merge_graphs \
-t exon_skip,intron_retention,alt_3prime,alt_5prime,mutex_exons,mult_exon_skip \
> ./output_${CHR}/spladder.log 2>&1
```

Best, r

**Comment by rschulzUK** [comment]
A third case: human Chr 7. Core-dumped previously on another machine (likely due to a buggy pthreads). Ended up not terminating on a different machine, again while handling multi-exon skips.

**Comment by warrenmcg** [comment]
Hi @rschulzUK,

I was having the same problem, and using gdb, I was able to see that it is not in fact an infinite loop, but just a section of code that needs to be optimized (detect_mult_skips in [modules/alt_splice/detect.py](https://github.com/ratschlab/spladder/blob/master/python/modules/alt_splice/detect.py#L47)). I had difficulty myself, and pinpointed a gene (Meg-3 in mice) that caused a major lag, even though my machine has got plenty of processing power behind it. The gene is already a very large lncRNA, but SplAdder had identified 3K+ edges in the splice graph. This very large number disqualified it from the other splice events, but it was included in the muli-exon-skip analysis, though I was unable to check how many potential events it had (was unable to print out edge[0].shape[0] from line 47). 

The algorithm for quantifying multiple exon skips has to check all of the exons and splices in between to check "Percent spliced in" vs "percent spliced out", so the algorithm appears to run around O(n^3) in the worst case (3 nested for loops), so that's going to take a while for 3K possible exons.

@akahles, I know you're busy settling in and writing grants, but your comments on this issue are welcome.

**Comment by akahles** [comment]
Please re-open if still relevant.
