### ISSUE TITLE
Skewed p-values spladder_test.py

### ISSUE THREAD

**Issue by ajw2329** [ratschlab/spladder#42]
Hello,

Thanks again for writing such a great tool - I'm getting a lot of good use out of it!  I write to ask about p-value distributions generated with spladder_test.py.  I always seem to get a massive peak of p-values exactly equal to 1.  The events with p=1 all seem to have calculated psi-values (no NaNs or anything like that).  My understanding was that even in the case where there are no significant changes the p-values should be uniformly distributed.  Here's a sample histogram - these are the frequencies of the unadjusted p-values:
![rplot](https://cloud.githubusercontent.com/assets/12420913/17918262/409eec38-6978-11e6-9051-ac8a353d828c.png)

I ran SplAdder (from the dev branch) with the following command: 

python2.7 ~/spladder-development/python/spladder.py -b $bams -o $outdir -a $anno -v y -M merge_graphs -t exon_skip,intron_retention,alt_3prime,alt_5prime,mutex_exons,mult_exon_skip -c 3     --ignore_mismatches=y 

and SplAdder test (also from the dev branch) as follows:

python2.7 ~/spladder-development/python/spladder_test.py -a $cond_A -b $cond_B -o $outdir --labelA=Ctrl_24h --labelB=Emet -v y -M merge_graphs -t $event_types -c 3 -n 100

Possibly this is normal for this sort of test?  I am not a statistician, and most of the prior discussion that I can find seems centered around gene expression, not alternative splicing.  

Thanks again!
Best,
Andrew

**Comment by akahles** [comment]
Hi Andrew,

Sorry for not getting back to you earlier - there has been just too much on my plate recently. 

We have observed a similar skew in some of our test sets and we are working on a better calibration. This will hopefully get better soon in the next version. 

As it is not a typical software bug as such, I would close this for now. Please re-open if you feel otherwise and I will update here when there is progress.

Cheers,
Andre

**Comment by ajw2329** [comment]
Thanks very much!
