### ISSUE TITLE
Warnings for human gencode.v25.primary_assembly.annotation.gtf

### ISSUE THREAD

**Issue by heseber** [ratschlab/spladder#49]
Dear Andre, dear all,

I get some warnings when working with gencode.v25.primary_assembly.annotation.gtf. Should I be worried about these? The number of excluded genes seems to be extremely high to me, and the question is how many genes remain after this cleanup afterall. Thanks for your help!

Regards
Henrik

```
WARNING: removing 34008 genes from given annotation that overlap to each other:
list of excluded genes written to: [...]/gencode.v25.primary_assembly.annotation.gtf.genes_excluded_gene_overlap
WARNING: removing 44 genes from given annotation that share exact exon coordines:
list of excluded exons written to: [...]/gencode.v25.primary_assembly.annotation.gtf.genes_excluded_exon_shared
WARNING: removing 6590 genes from given annotation that have at least one transcript with overlapping exons.
list of excluded genes written to: [...]/gencode.v25.primary_assembly.annotation.gtf.genes_excluded_exon_overlap
```

**Comment by heseber** [comment]
I forgot to mention: 
```
python $spladderScript -b $bamlinks -a $GTF -o $OUTDIR
```
Version pulled from github on Dec 8th, 10:52 CET.

**Comment by DarioS** [comment]
Those all seem like situations spladder should be able to cope with automatically. For example, if genes overlap each other, consider only the distinct exons of those genes. If the overlapping exons are on opposite strands, then they should be retained, if the dataset is strand-specific RNA-seq. I guess that the journal reviewers for spladder didn't bother trying the software themselves, since evidently it doesn't work properly in common scenarios (like the majority of bioinformatics software).

**Comment by akahles** [comment]
The handling of overlapping genes has been improved in the recent versions. Only new introns with conflicting gene annotations and exonic segments with conflicting gene annotations are now ignored.
Introns are handled in a strand-specific manner.
