### ISSUE TITLE
1.2.1 commands and output format

### ISSUE THREAD

**Issue by jfass** [ratschlab/spladder#83]
* spladder version: 1.2.1
* Python version: 2.7.12
* Operating System: Ubuntu 16

### Description

Using 1.2.1 for now (since the latest was giving me an hdf5 error; reported in issue #71). Have questions about command and output.

### What I Did

```
spladder build --parallel 16 --annotation RawData/gencode.v19.annotation.gtf --bams sample.bam --readlen 152 -o sample.spladder
```

So, I don't see a separate subcommand structure ... the command I ran above worked. Did spladder just ignore the "build"? And, if so, then I guess I ran with the default of option -T y, which means that testing was done. But, would it be done on a single sample, as in, versus the reference? The stdout included 5 separate lines saying "Nothing to report" for each event type. The hdf5 files have "confirmed" Datasets, but they seem to be all zeros. Could you elaborate a little on what this means? Mainly - was there any actual testing done with one sample.

Thanks,
~Joe

**Comment by akahles** [comment]
Hi Joe,
The `build` will just be ignored. However, I would not advise to run the older versions of SplAdder. I am working on issue #71 now, which is caused by SplAdder not detecting any events. Once this problem is solved, the testing should work as well. 

Your observation that all "confirmed" values are zero means that SplAdder can not detect any read evidence for any of the events in any of your samples, which leads to no events being available for testing. 
 
How were your BAM files generated? Did you use the same genome and annotation version as for the SplAdder run?

Thanks and Cheers,

Andre
